### ISSUE TITLE
leetup test encounters an error

### ISSUE THREAD

**Issue by hao-lee** [dragfire/leetup#40]
```
~# leetup test longest-common-prefix.py -t '["1"]'

⣸ Waiting for judge result!thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/service/leetcode.rs:653:64            
stack backtrace:                                                                                                                              
⣇ Waiting for judge result!   0:     0x557469683e50 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3                       
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:9
0:5                                                                    
   1:     0x557469683e50 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7      
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557469683e50 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72                                             
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x557469683e50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5574696a6bff - core::fmt::write::h3b84512577ca38a8   
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x55746967d8b2 - std::io::Write::write_fmt::h465f8feea02e2aa1 
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x557469685fc5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x557469685fc5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x557469685fc5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x557469685a73 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5574696865cd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x557469686137 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:495:13
  12:     0x55746968430c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5574696860c9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x55746915f471 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x55746915f3bd - core::panicking::panic::h10ab123a4b13cc79
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
  16:     0x557469192098 - <leetup::service::leetcode::Leetcode as leetup::service::provider::ServiceProvider>::problem_test::h9240a17f70ab901
5
  17:     0x55746917ef7f - leetup::cmd::process::h314518d541f20451
  18:     0x55746915fee6 - leetup::main::ha430b6c68499d4fc
  19:     0x55746915ffb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf47a4d505712b6df
  20:     0x55746915ff89 - std::rt::lang_start::{{closure}}::h1aa4320a6abffc5e
  21:     0x557469686aca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  22:     0x557469686aca - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  23:     0x557469686aca - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  24:     0x557469686aca - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  25:     0x557469686aca - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  26:     0x55746915ff72 - main
⡧ Waiting for judge result!  27:     0x7fcdca0271e2 - __libc_start_main 
  28:     0x55746915fb59 - _start
  29:                0x0 - <unknown>

```

**Comment by dragfire** [comment]
This is related to this issue: #39 
I haven't had much time to work on this. I would accept a PR.
